apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
spec:
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
        run: hoge
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http-port
          containerPort: 50000